### ISSUE TITLE
Updating IBMwatson.js file

### ISSUE THREAD

**Issue by akashdave11** [initialstate/pubnub-live-twitter-dashboard#1]
Since alchempyapi has been stopped what should i enter as the apikey since the credentials are in username and password format

**Comment by RChloe** [comment]
I believe that you'll need to change the **apiURL** on line 10 to "https://gateway.watsonplatform.net/natural-language-understanding/api/v1/analyze" and then replace the **apiKey** with username and password constants.  Be sure to change line 22 to have both of those.

It looks like the response might have changed, meaning that line 49-61 may need updating. You can see example responses here: [https://www.ibm.com/watson/developercloud/natural-language-understanding/api/v1/index.html#sentiment](https://www.ibm.com/watson/developercloud/natural-language-understanding/api/v1/index.html#sentiment)

**Comment by akashdave11** [comment]
Thankyou for your response RChole

I Updated the code with the username password constants and changed line 22 accordingly.

However For the second part i.e. lines 49-61. I am not so sure how to go about updating them. Any kind of help would be appreciated.

**Comment by akashdave11** [comment]
@RChloe 

Do you have the updated version of the file? I am finding it rather hard to update the code to the newer  version that is Watson NLU

**Comment by RChloe** [comment]
I added an updated file here: https://github.com/initialstate/pubnub-live-twitter-dashboard/blob/master/IBMWatsonUpdated.js

It is not as functional as the old version as it does not seem to work without much of the code commented out. I believe this is an issue that has to be resolved by PubNub and have already contacted them about it. 

Currently this block will only return the sentiment type and score (so the SentimentSubscribeCallback() in pubnubStream will need to be edited accordingly).

**Comment by RChloe** [comment]
UPDATE: Uncommented the new block script because it works now. The error only happens on the first publish and PubNub should have it fixed tomorrow.

**Comment by divy-kangeyan** [comment]
Hi @RChloe,
                     I still cannot make it work with the updated script that you posted. Is this the correct file to look for https://github.com/initialstate/pubnub-live-twitter-dashboard/blob/master/IBMWatsonUpdated.js?

I am only getting this as the output
22:45:08  publish: { "session_id": 1, "text": "I am happy!" }
